name: Utilities
version: '${version}'
main: com.github.m4kvn.spigot.spigotutilities.Main
api-version: 1.19
commands:
  utilities:
    description: This is utilities command.
    usage: /<command>
    aliases: [ "ut" ]
  evolution:
    description: This is evolution command.
    usage: /<command> <enchantment>
    aliases: [ "evo" ]